import { describe, it, expect } from "vitest";
import { readFileSync, existsSync, readdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  APPROVED_MIGRATIONS,
  EXPECTED_MIGRATION_COUNT,
  EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME,
  migrationsAuthoredBefore,
  sortsAfterAll,
} from "./migration-inventory";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(__dirname, "..");

// This permanent test is repository-history independent: no git status, git
// diff, git log, branch name, commit SHA, PR state or remote-ref dependency. It
// also performs NO network access — every provenance URL is validated
// structurally, never fetched.
//
// EQ-S2-C ships v2 as an ADDITIVE DELTA of 201 new non-putter models: 201 new
// rows and their 201 provenance rows, on top of the closed 51-model v1
// baseline, which it never restates and never collides with.
//
// The migration filename is generated by the Supabase CLI and is therefore
// never written literally here. Every assertion about it resolves through
// EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME in the shared migration inventory,
// so a fabricated or renamed file fails rather than quietly passing.

function readBytes(relativePath: string): Buffer {
  return readFileSync(path.join(repoRoot, relativePath));
}

function readText(relativePath: string): string {
  return readBytes(relativePath).toString("utf8");
}

function sha256(value: Buffer): string {
  return createHash("sha256").update(value).digest("hex");
}

const DATA_FILE = "data/equipment-catalog-non-putters-v2.json";
const GENERATOR_FILE = "scripts/generate-equipment-catalog-non-putters-v2.mjs";
const TEST_FILE = "lib/equipment-non-putter-catalog-v2-schema.test.ts";
const NON_PUTTER_V1_FILE = "data/equipment-catalog-non-putters-v1.json";
const PUTTER_V1_FILE = "data/equipment-catalog-putters-v1.json";

// The closed v1 artifact families, the shared type surface and the B2
// provenance-vocabulary migration. EQ-S2-C must not touch any of them. If a
// later authorized slice legitimately changes one, that slice updates the digest
// here deliberately — silent drift is the failure mode these pins exist to
// prevent.
//
// The accepted v2 source artifact is pinned alongside them: the generator, this
// test and the future migration all derive from those exact bytes.
const PROTECTED_DIGESTS: Record<string, string> = {
  "data/equipment-catalog-non-putters-v1.json":
    "111de8d161ce2f08b79730c15981c6072e81b5e550a989d8cc99eddbb07ed501",
  "scripts/generate-equipment-catalog-non-putters-v1.mjs":
    "520eeb5466abd447e17f54b7413a3c76d99cd9ab4c6fb52b23c02c0b245d3a1b",
  "supabase/migrations/20260820132900_equipment_non_putter_catalog_v1.sql":
    "9c11181dc15066228d8a04fedc07872adf0e5847404eee4a4540b528b16e4dcd",
  "lib/equipment-non-putter-catalog-schema.test.ts":
    "d79392cdd6755e58e2d07ca26a7dc04e5642ad7df46826e1cf4dc03a798e81c3",
  "data/equipment-catalog-putters-v1.json":
    "0a73e9460d1f416b8af04838dc983df5bcb40ea9f4fa169b9975e50a2b502029",
  "scripts/generate-equipment-catalog-putters-v1.mjs":
    "89b40a7a23c80b4377019eb1548395086d5ea9d36584ad6cbd8ec3226184d287",
  "supabase/migrations/20260725174239_equipment_putter_catalog_v1.sql":
    "f133d266395879e208ad3bc615a77f8b6d394f98608263e22011d07b82df9ed4",
  "lib/equipment-catalog-schema.test.ts":
    "7fff61c8005d0517b942344180cbd68a12e640767132213c942dc6101cca59d9",
  "types/database.ts":
    "7f3e5525a792b6ab494e36c0769dee44d8dd5ae3c8f04679bd166bb93d3c0810",
  "supabase/migrations/20260903213417_equipment_model_source_category_provenance.sql":
    "34d8d1854523ef8516d89f796eddf7ef383dbe0dccb66a24fc5885318c9b93ae",
  [DATA_FILE]: "26c8fae856c53bc8c3e034a2306b9bc2f028e3029476bfcbcde0fb5aefd87c56",
};

const UUID_NAMESPACE = "05690d1f-f17d-5ab8-a2b6-ef0328a2783a";
const CATALOG_NAME = "equipment-catalog-non-putters-v2";
const VERIFIED_ON = "2026-09-04";

const EXPECTED_MODEL_COUNT = 201;
const EXPECTED_SOURCE_COUNT = 201;
const EXPECTED_EXISTING_COUNT = 51;
const EXPECTED_COMBINED_COUNT = 252;

const EXPECTED_MANUFACTURERS = ["callaway", "cobra", "mizuno", "ping", "taylormade", "titleist"];
const EXPECTED_CLUB_TYPES = ["Driver", "Wood", "Hybrid", "Iron", "Wedge"];
const CLUB_TYPE_ENUM_VALUES = ["Driver", "Wood", "Hybrid", "Iron", "Wedge", "Putter"];

// The authoritative 30-cell coverage contract. Two cells are legitimately zero,
// so there is deliberately no universal "every cell is populated" assertion.
const EXPECTED_MATRIX: Record<string, Record<string, number>> = {
  taylormade: { Driver: 7, Wood: 6, Hybrid: 5, Iron: 10, Wedge: 5 },
  callaway: { Driver: 10, Wood: 18, Hybrid: 15, Iron: 26, Wedge: 8 },
  titleist: { Driver: 4, Wood: 4, Hybrid: 2, Iron: 6, Wedge: 0 },
  ping: { Driver: 9, Wood: 7, Hybrid: 3, Iron: 11, Wedge: 2 },
  mizuno: { Driver: 1, Wood: 0, Hybrid: 1, Iron: 8, Wedge: 1 },
  cobra: { Driver: 9, Wood: 8, Hybrid: 4, Iron: 10, Wedge: 1 },
};

const EXPECTED_CLUB_TYPE_TOTALS: Record<string, number> = {
  Driver: 40,
  Wood: 43,
  Hybrid: 30,
  Iron: 71,
  Wedge: 17,
};

const EXPECTED_POST_CLUB_TYPE_TOTALS: Record<string, number> = {
  Driver: 46,
  Wood: 49,
  Hybrid: 36,
  Iron: 77,
  Wedge: 23,
  Putter: 21,
};

const EXPECTED_SOURCE_TYPE_DISTRIBUTION: Record<string, number> = {
  official_product_page: 200,
  official_spec_pdf: 0,
  official_archive: 0,
  official_category_page: 1,
};

const SOURCE_NAME_SUFFIX: Record<string, string> = {
  official_product_page: "official product page",
  official_spec_pdf: "official specification PDF",
  official_archive: "official archive",
  official_category_page: "official category page",
};

const SOLE_CATEGORY_PAGE_SOURCE = {
  canonical_name: "Mizuno ST-Max Hybrid",
  source_name: "Mizuno ST-Max Hybrid official category page",
  source_url: "https://mizunogolf.com/us/hybrids/",
  verified_at: "2026-09-04",
};

const ALLOWED_SOURCE_DOMAINS = [
  "taylormadegolf.com",
  "www.taylormadegolf.com",
  "callawaygolf.com",
  "www.callawaygolf.com",
  "titleist.com",
  "www.titleist.com",
  "ping.com",
  "www.ping.com",
  "mizunogolf.com",
  "www.mizunogolf.com",
  "cobragolf.com",
  "www.cobragolf.com",
];

const TRACKING_QUERY_PARAM_PATTERN =
  /(?:^|[?&])(utm_[a-z]+|aff|affid|affiliate|ref|clickid|gclid|fbclid|irclickid)=/i;

const PROHIBITED_FIELD_NAMES = [
  "price", "retail_price", "inventory", "stock",
  "affiliate", "affiliate_url", "tracking", "tracking_url",
  "sponsorship", "sponsor", "ranking", "tour_usage",
  "endorsement", "player_recommendation", "marketing_copy", "description",
  "image", "image_url", "logo", "logo_url",
  "ai_score", "recommended_player", "fitting_conclusion",
  "loft", "lofts", "loft_options", "shaft", "shafts", "shaft_flex",
  "shaft_flex_options", "shaft_weight", "club_number", "sku", "grind", "grinds",
  "bounce", "putter_specs",
];

const MODEL_FIELDS = [
  "catalog_key", "manufacturer_slug", "club_type", "brand_line", "brand_line_slug",
  "model_family", "model_family_slug", "canonical_name", "slug", "normalized_name",
  "model_year", "release_year", "is_active", "specifications", "sources",
];

const SOURCE_FIELDS = ["source_type", "source_name", "source_url", "verified_at"];

const SLUG_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const CATALOG_KEY_PATTERN = /^[a-z0-9]+(\/[a-z0-9-]+)+$/;

// ---------------------------------------------------------------------------
// Independent RFC 4122 UUIDv5
//
// Implemented here from first principles. Importing the generator's helper
// would make this test agree with the generator by construction rather than
// verify it.
// ---------------------------------------------------------------------------

function uuidToBytes(uuid: string): Buffer {
  const hex = uuid.replace(/-/g, "");
  const bytes = Buffer.alloc(16);
  for (let i = 0; i < 16; i += 1) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

function bytesToUuid(bytes: Buffer): string {
  const hex = [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    hex.slice(12, 16),
    hex.slice(16, 20),
    hex.slice(20, 32),
  ].join("-");
}

function uuidv5(namespaceUuid: string, name: string): string {
  const hash = createHash("sha1")
    .update(uuidToBytes(namespaceUuid))
    .update(Buffer.from(name, "utf8"))
    .digest();
  const bytes = Buffer.from(hash.subarray(0, 16));
  bytes[6] = (bytes[6] & 0x0f) | 0x50;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  return bytesToUuid(bytes);
}

function normalizeName(canonicalName: string): string {
  return canonicalName.toLowerCase().replace(/[^a-z0-9]/g, "");
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

type Source = {
  source_type: string;
  source_name: string;
  source_url: string;
  verified_at: string;
};

type Model = {
  catalog_key: string;
  manufacturer_slug: string;
  club_type: string;
  brand_line: string | null;
  brand_line_slug: string | null;
  model_family: string | null;
  model_family_slug: string | null;
  canonical_name: string;
  slug: string;
  normalized_name: string;
  model_year: number | null;
  release_year: number | null;
  is_active: boolean;
  specifications: Record<string, unknown>;
  sources: Source[];
};

const rawCatalog = readText(DATA_FILE);
const catalog = JSON.parse(rawCatalog) as {
  schema_version: number;
  catalog_name: string;
  uuid_namespace: string;
  verified_on: string;
  manufacturers: unknown[];
  models: Model[];
};
const models = catalog.models;
const sources = models.flatMap((model) => model.sources);

// The two closed v1 catalogs, loaded independently of the generator. The putter
// artifact predates club_type in the catalog JSON: every one of its rows is a
// Putter by construction.
const nonPutterV1 = JSON.parse(readText(NON_PUTTER_V1_FILE)) as { models: Model[] };
const putterV1 = JSON.parse(readText(PUTTER_V1_FILE)) as {
  models: Omit<Model, "club_type" | "specifications">[];
};
const existingModels: Model[] = [
  ...nonPutterV1.models,
  ...putterV1.models.map((m) => ({ ...m, club_type: "Putter" }) as Model),
];

function effectiveIdentity(model: Model): string {
  return [
    model.manufacturer_slug,
    model.club_type,
    model.normalized_name,
    model.model_year ?? 0,
  ].join("|");
}

// One --emit run, reused by every SQL assertion. A second run is compared
// against it to prove determinism.
const emittedSql = execFileSync(process.execPath, [path.join(repoRoot, GENERATOR_FILE), "--emit"], {
  cwd: repoRoot,
  maxBuffer: 64 * 1024 * 1024,
}).toString("utf8");

describe("EQ-S2-C v2 — artifact scope and protected baseline", () => {
  it("ships the accepted v2 source artifact, its generator and this test", () => {
    for (const file of [DATA_FILE, GENERATOR_FILE, TEST_FILE]) {
      expect(existsSync(path.join(repoRoot, file))).toBe(true);
    }
  });

  it("leaves the closed v1 artifacts, the shared types and the B2 migration byte-unchanged", () => {
    for (const [file, digest] of Object.entries(PROTECTED_DIGESTS)) {
      expect(`${file}:${sha256(readBytes(file))}`).toBe(`${file}:${digest}`);
    }
  });

  it("uses LF line endings and exactly one trailing newline in the v2 source", () => {
    expect(rawCatalog.includes("\r")).toBe(false);
    expect(rawCatalog.endsWith("\n")).toBe(true);
    expect(rawCatalog.endsWith("\n\n")).toBe(false);
  });
});

describe("EQ-S2-C v2 — root contract", () => {
  it("declares the locked root contract", () => {
    expect(Object.keys(catalog)).toEqual([
      "schema_version",
      "catalog_name",
      "uuid_namespace",
      "verified_on",
      "manufacturers",
      "models",
    ]);
    expect(catalog.schema_version).toBe(1);
    expect(catalog.catalog_name).toBe(CATALOG_NAME);
    expect(catalog.uuid_namespace).toBe(UUID_NAMESPACE);
    expect(catalog.verified_on).toBe(VERIFIED_ON);
  });

  it("introduces no new parent manufacturer", () => {
    expect(Array.isArray(catalog.manufacturers)).toBe(true);
    expect(catalog.manufacturers).toHaveLength(0);
  });

  it("contains exactly 201 models and 201 provenance sources", () => {
    expect(models).toHaveLength(EXPECTED_MODEL_COUNT);
    expect(sources).toHaveLength(EXPECTED_SOURCE_COUNT);
    expect(models.every((m) => m.sources.length === 1)).toBe(true);
  });

  it("uses exactly the six locked manufacturers and five non-putter club types", () => {
    expect([...new Set(models.map((m) => m.manufacturer_slug))].sort()).toEqual(
      [...EXPECTED_MANUFACTURERS].sort()
    );
    expect([...new Set(models.map((m) => m.club_type))].sort()).toEqual(
      [...EXPECTED_CLUB_TYPES].sort()
    );
  });

  it("contains no Putter row", () => {
    expect(models.filter((m) => m.club_type === "Putter")).toHaveLength(0);
  });

  it("declares exactly the locked model and source field sets", () => {
    for (const model of models) {
      expect(Object.keys(model)).toEqual(MODEL_FIELDS);
      for (const source of model.sources) {
        expect(Object.keys(source)).toEqual(SOURCE_FIELDS);
      }
    }
  });
});

describe("EQ-S2-C v2 — exact coverage matrix", () => {
  it("matches all 30 manufacturer/club-type cells exactly, zeros included", () => {
    const actual: Record<string, Record<string, number>> = {};
    for (const manufacturer of EXPECTED_MANUFACTURERS) {
      actual[manufacturer] = {};
      for (const clubType of EXPECTED_CLUB_TYPES) {
        actual[manufacturer][clubType] = models.filter(
          (m) => m.manufacturer_slug === manufacturer && m.club_type === clubType
        ).length;
      }
    }
    expect(actual).toEqual(EXPECTED_MATRIX);
  });

  it("keeps the two legitimately empty cells empty", () => {
    expect(models.filter((m) => m.manufacturer_slug === "titleist" && m.club_type === "Wedge")).toHaveLength(0);
    expect(models.filter((m) => m.manufacturer_slug === "mizuno" && m.club_type === "Wood")).toHaveLength(0);
  });

  it("matches the locked global club-type totals", () => {
    for (const [clubType, expected] of Object.entries(EXPECTED_CLUB_TYPE_TOTALS)) {
      expect(`${clubType}:${models.filter((m) => m.club_type === clubType).length}`).toBe(
        `${clubType}:${expected}`
      );
    }
    const matrixTotal = Object.values(EXPECTED_MATRIX)
      .flatMap((row) => Object.values(row))
      .reduce((a, b) => a + b, 0);
    expect(matrixTotal).toBe(EXPECTED_MODEL_COUNT);
  });

  it("projects the locked post-deployment club-type totals", () => {
    for (const clubType of CLUB_TYPE_ENUM_VALUES) {
      const projected =
        existingModels.filter((m) => m.club_type === clubType).length +
        models.filter((m) => m.club_type === clubType).length;
      expect(`${clubType}:${projected}`).toBe(`${clubType}:${EXPECTED_POST_CLUB_TYPE_TOTALS[clubType]}`);
    }
  });
});

describe("EQ-S2-C v2 — uniqueness and global collision", () => {
  it("keeps catalog keys, slugs, canonical names and effective identities unique within v2", () => {
    expect(new Set(models.map((m) => m.catalog_key)).size).toBe(EXPECTED_MODEL_COUNT);
    expect(new Set(models.map((m) => m.slug)).size).toBe(EXPECTED_MODEL_COUNT);
    expect(new Set(models.map((m) => m.canonical_name)).size).toBe(EXPECTED_MODEL_COUNT);
    expect(new Set(models.map(effectiveIdentity)).size).toBe(EXPECTED_MODEL_COUNT);
  });

  it("loads exactly the 51-model closed v1 baseline, itself internally unique", () => {
    expect(nonPutterV1.models).toHaveLength(30);
    expect(putterV1.models).toHaveLength(21);
    expect(existingModels).toHaveLength(EXPECTED_EXISTING_COUNT);
    expect(new Set(existingModels.map((m) => m.catalog_key)).size).toBe(EXPECTED_EXISTING_COUNT);
    expect(new Set(existingModels.map((m) => m.slug)).size).toBe(EXPECTED_EXISTING_COUNT);
    expect(new Set(existingModels.map((m) => m.canonical_name)).size).toBe(EXPECTED_EXISTING_COUNT);
    expect(new Set(existingModels.map(effectiveIdentity)).size).toBe(EXPECTED_EXISTING_COUNT);
  });

  it("collides with the existing 51 in none of the four identity classes", () => {
    const classes: [string, (m: Model) => string][] = [
      ["catalog_key", (m) => m.catalog_key],
      ["slug", (m) => m.slug],
      ["canonical_name", (m) => m.canonical_name],
      ["effective identity", effectiveIdentity],
    ];
    for (const [label, project] of classes) {
      const existing = new Set(existingModels.map(project));
      const intersection = models.map(project).filter((value) => existing.has(value));
      expect(`${label}:${intersection.length}`).toBe(`${label}:0`);
    }
  });

  it("projects exactly 252 unique values in every identity class", () => {
    const classes: [string, (m: Model) => string][] = [
      ["catalog_key", (m) => m.catalog_key],
      ["slug", (m) => m.slug],
      ["canonical_name", (m) => m.canonical_name],
      ["effective identity", effectiveIdentity],
    ];
    for (const [label, project] of classes) {
      const combined = new Set([...existingModels.map(project), ...models.map(project)]);
      expect(`${label}:${combined.size}`).toBe(`${label}:${EXPECTED_COMBINED_COUNT}`);
    }
  });
});

describe("EQ-S2-C v2 — deterministic identity", () => {
  it("reproduces the RFC 4122 UUIDv5 reference vector", () => {
    expect(uuidv5("6ba7b810-9dad-11d1-80b4-00c04fd430c8", "python.org")).toBe(
      "886313e1-3b8a-5372-9b90-0c9aee199e5d"
    );
  });

  it("emits every model id as uuidv5(namespace, \"model:<catalog_key>\") and resolves its parent by slug", () => {
    const missing: string[] = [];
    for (const model of models) {
      const id = uuidv5(UUID_NAMESPACE, `model:${model.catalog_key}`);
      const row =
        `  (${sqlString(id)}, (select id from public.equipment_manufacturers where slug = ` +
        `${sqlString(model.manufacturer_slug)}), ${sqlString(model.club_type)}::public.club_type_enum, ` +
        `${sqlString(model.canonical_name)}, ${sqlString(model.slug)}, ${sqlString(model.normalized_name)}, ` +
        `null, '{}'::jsonb, true, ${sqlString(model.catalog_key)},`;
      if (!emittedSql.includes(row)) missing.push(model.catalog_key);
    }
    expect(missing).toEqual([]);
  });

  it("emits every source id as uuidv5(namespace, \"source:<catalog_key>:<source_url>\")", () => {
    const missing: string[] = [];
    for (const model of models) {
      const modelId = uuidv5(UUID_NAMESPACE, `model:${model.catalog_key}`);
      for (const source of model.sources) {
        const sourceId = uuidv5(UUID_NAMESPACE, `source:${model.catalog_key}:${source.source_url}`);
        const row =
          `  (${sqlString(sourceId)}, ${sqlString(modelId)}, ${sqlString(source.source_type)}, ` +
          `${sqlString(source.source_name)}, ${sqlString(source.source_url)}, ` +
          `${sqlString(source.verified_at)}::date)`;
        if (!emittedSql.includes(row)) missing.push(`${model.catalog_key} -> ${source.source_url}`);
      }
    }
    expect(missing).toEqual([]);
  });

  it("derives 201 distinct model ids and 201 distinct source ids", () => {
    const modelIds = models.map((m) => uuidv5(UUID_NAMESPACE, `model:${m.catalog_key}`));
    const sourceIds = models.flatMap((m) =>
      m.sources.map((s) => uuidv5(UUID_NAMESPACE, `source:${m.catalog_key}:${s.source_url}`))
    );
    expect(new Set(modelIds).size).toBe(EXPECTED_MODEL_COUNT);
    expect(new Set(sourceIds).size).toBe(EXPECTED_SOURCE_COUNT);
    expect(new Set([...modelIds, ...sourceIds]).size).toBe(EXPECTED_MODEL_COUNT + EXPECTED_SOURCE_COUNT);
  });

  it("never writes a manufacturer id as a literal", () => {
    const manufacturerIdRows = emittedSql.match(/insert into public\.equipment_manufacturers/g);
    expect(manufacturerIdRows).toBeNull();
    expect(
      (emittedSql.match(/\(select id from public\.equipment_manufacturers where slug = /g) ?? []).length
    ).toBe(EXPECTED_MODEL_COUNT);
  });
});

describe("EQ-S2-C v2 — data boundary", () => {
  it("leaves model_year, release_year, brand_line and brand_line_slug null across the delta", () => {
    expect(models.filter((m) => m.model_year === null)).toHaveLength(EXPECTED_MODEL_COUNT);
    expect(models.filter((m) => m.release_year === null)).toHaveLength(EXPECTED_MODEL_COUNT);
    expect(models.filter((m) => m.brand_line === null)).toHaveLength(EXPECTED_MODEL_COUNT);
    expect(models.filter((m) => m.brand_line_slug === null)).toHaveLength(EXPECTED_MODEL_COUNT);
  });

  it("keeps specifications an empty object and every model active", () => {
    for (const model of models) {
      expect(Object.keys(model.specifications)).toEqual([]);
      expect(model.is_active).toBe(true);
    }
  });

  it("derives normalized_name deterministically from canonical_name", () => {
    for (const model of models) {
      expect(model.normalized_name).toBe(normalizeName(model.canonical_name));
    }
  });

  it("uses well-formed catalog keys, all carrying the /v1 model-identity suffix", () => {
    for (const model of models) {
      expect(CATALOG_KEY_PATTERN.test(model.catalog_key)).toBe(true);
      expect(model.catalog_key.endsWith("/v1")).toBe(true);
      expect(model.catalog_key.startsWith(`${model.manufacturer_slug}/`)).toBe(true);
      expect(SLUG_PATTERN.test(model.slug)).toBe(true);
    }
  });

  it("pairs model_family with its slug", () => {
    for (const model of models) {
      if (model.model_family === null) {
        expect(model.model_family_slug).toBeNull();
      } else {
        expect(model.model_family.trim()).not.toBe("");
        expect(SLUG_PATTERN.test(model.model_family_slug ?? "")).toBe(true);
      }
    }
  });

  it("never promotes loft, shaft, club number, SKU or any commercial field into catalog data", () => {
    const seen = new Set<string>();
    for (const model of models) {
      Object.keys(model).forEach((key) => seen.add(key));
      for (const source of model.sources) Object.keys(source).forEach((key) => seen.add(key));
    }
    for (const prohibited of PROHIBITED_FIELD_NAMES) {
      expect(`${prohibited}:${seen.has(prohibited)}`).toBe(`${prohibited}:false`);
    }
  });

  it("carries no putter-spec payload and no evidence-pack field", () => {
    for (const evidenceOnly of [
      "batch_row_id",
      "manufacturer_name",
      "current_catalog_title",
      "eligibility_url",
      "evidence_note",
      "existing_catalog_collision_result",
      "putter_specs",
    ]) {
      expect(rawCatalog.includes(`"${evidenceOnly}"`)).toBe(false);
    }
  });
});

describe("EQ-S2-C v2 — official provenance", () => {
  it("carries exactly one source per model", () => {
    expect(models.every((m) => m.sources.length === 1)).toBe(true);
    expect(sources).toHaveLength(EXPECTED_SOURCE_COUNT);
  });

  it("matches the locked 200 + 1 provenance split exactly", () => {
    for (const [sourceType, expected] of Object.entries(EXPECTED_SOURCE_TYPE_DISTRIBUTION)) {
      expect(`${sourceType}:${sources.filter((s) => s.source_type === sourceType).length}`).toBe(
        `${sourceType}:${expected}`
      );
    }
  });

  it("uses the official_category_page fallback for exactly one locked model", () => {
    const categoryModels = models.filter((m) =>
      m.sources.some((s) => s.source_type === "official_category_page")
    );
    expect(categoryModels).toHaveLength(1);
    const [model] = categoryModels;
    expect(model.canonical_name).toBe(SOLE_CATEGORY_PAGE_SOURCE.canonical_name);
    expect(model.club_type).toBe("Hybrid");
    expect(model.manufacturer_slug).toBe("mizuno");
    expect(model.sources[0].source_name).toBe(SOLE_CATEGORY_PAGE_SOURCE.source_name);
    expect(model.sources[0].source_url).toBe(SOLE_CATEGORY_PAGE_SOURCE.source_url);
    expect(model.sources[0].verified_at).toBe(SOLE_CATEGORY_PAGE_SOURCE.verified_at);
  });

  it("derives every source_name from its canonical name and source type", () => {
    for (const model of models) {
      for (const source of model.sources) {
        expect(source.source_name).toBe(
          `${model.canonical_name} ${SOURCE_NAME_SUFFIX[source.source_type]}`
        );
      }
    }
  });

  it("uses HTTPS on official manufacturer hostnames only, with no fragment", () => {
    for (const source of sources) {
      const parsed = new URL(source.source_url);
      expect(parsed.protocol).toBe("https:");
      expect(ALLOWED_SOURCE_DOMAINS).toContain(parsed.hostname);
      expect(parsed.hash).toBe("");
    }
  });

  it("carries no tracking or affiliate parameter", () => {
    for (const source of sources) {
      const parsed = new URL(source.source_url);
      expect(TRACKING_QUERY_PARAM_PATTERN.test(parsed.search)).toBe(false);
    }
  });

  it("requires a .pdf pathname for every official_spec_pdf source", () => {
    for (const source of sources) {
      if (source.source_type === "official_spec_pdf") {
        expect(new URL(source.source_url).pathname.toLowerCase().endsWith(".pdf")).toBe(true);
      }
    }
  });

  it("stamps every source with the locked verification date", () => {
    for (const source of sources) {
      expect(source.verified_at).toBe(VERIFIED_ON);
    }
  });

  it("never cites a retailer, marketplace, review site, forum or search page", () => {
    // Matched on registrable hostname, never as a substring: "golf.com" is a
    // forbidden publisher, while "mizunogolf.com" is an official manufacturer
    // domain that merely ends in the same letters.
    const forbidden = [
      "amazon.com", "ebay.com", "golfgalaxy.com", "dickssportinggoods.com",
      "pgatoursuperstore.com", "2ndswing.com", "globalgolf.com", "rockbottomgolf.com",
      "worldwidegolfshops.com", "mygolfspy.com", "golfwrx.com", "golfdigest.com",
      "golf.com", "todays-golfer.com", "reddit.com", "facebook.com", "instagram.com",
      "youtube.com", "x.com", "twitter.com", "google.com", "bing.com",
      "duckduckgo.com", "wikipedia.org",
    ];
    for (const source of sources) {
      const hostname = new URL(source.source_url).hostname.toLowerCase();
      for (const host of forbidden) {
        const cited = hostname === host || hostname.endsWith(`.${host}`);
        expect(`${hostname}/${host}:${cited}`).toBe(`${hostname}/${host}:false`);
      }
    }
  });
});

describe("EQ-S2-C v2 — generator contract", () => {
  it("passes --validate-only and reports the locked totals", () => {
    const output = execFileSync(
      process.execPath,
      [path.join(repoRoot, GENERATOR_FILE), "--validate-only"],
      { cwd: repoRoot, maxBuffer: 16 * 1024 * 1024 }
    ).toString("utf8");
    expect(output).toContain("EQ-S2-C-V2-VALIDATE-OK");
    expect(output).toContain(`models                 : ${EXPECTED_MODEL_COUNT}`);
    expect(output).toContain(`sources                : ${EXPECTED_SOURCE_COUNT}`);
    expect(output).toContain("matrix cells exact     : 30/30");
    expect(output).toContain("collisions (key/slug/identity/name) : 0/0/0/0");
    expect(output).toContain(`projected catalog      : ${EXPECTED_COMBINED_COUNT}`);
    expect(output).toContain("files written          : 0");
  });

  it("emits byte-identical SQL across two independent runs", () => {
    const second = execFileSync(
      process.execPath,
      [path.join(repoRoot, GENERATOR_FILE), "--emit"],
      { cwd: repoRoot, maxBuffer: 64 * 1024 * 1024 }
    ).toString("utf8");
    expect(second).toBe(emittedSql);
  });

  it("writes no file: the generator has no fs write call at all", () => {
    const source = readText(GENERATOR_FILE);
    for (const forbidden of [
      "writeFileSync",
      "writeFile",
      "appendFileSync",
      "appendFile",
      "createWriteStream",
      "mkdirSync",
      "rmSync",
      "unlinkSync",
      "copyFileSync",
      "renameSync",
    ]) {
      expect(`${forbidden}:${source.includes(forbidden)}`).toBe(`${forbidden}:false`);
    }
  });

  it("requires an explicit mode and accepts only the three read-only modes", () => {
    const source = readText(GENERATOR_FILE);
    expect(source).toContain('const MODES = ["--validate-only", "--emit", "--check"];');
    expect(source).toContain("no mode selected");
    expect(source).toContain("exactly one mode may be selected");
    expect(source).toContain('unknown argument "${arg}"');
  });

  it("pins the SwingProAI UUID namespace and runs a known-vector self-check", () => {
    const source = readText(GENERATOR_FILE);
    expect(source).toContain(`const UUID_NAMESPACE = "${UUID_NAMESPACE}";`);
    expect(source).toContain("886313e1-3b8a-5372-9b90-0c9aee199e5d");
    expect(source).toContain("selfCheckUuidv5");
  });

  it("encodes the exact 30-cell matrix and never a universal per-cell minimum", () => {
    const source = readText(GENERATOR_FILE);
    for (const [manufacturer, row] of Object.entries(EXPECTED_MATRIX)) {
      const rendered = `${manufacturer}: { Driver: ${row.Driver}, Wood: ${row.Wood}, Hybrid: ${row.Hybrid}, Iron: ${row.Iron}, Wedge: ${row.Wedge} }`;
      expect(source).toContain(rendered);
    }
    expect(source.includes("MIN_ROWS_PER_CELL")).toBe(false);
  });

  it("declares all four official provenance classes", () => {
    const source = readText(GENERATOR_FILE);
    for (const sourceType of Object.keys(EXPECTED_SOURCE_TYPE_DISTRIBUTION)) {
      expect(source).toContain(sourceType);
    }
  });

  it("declares no runtime network dependency", () => {
    const source = readText(GENERATOR_FILE);
    for (const forbidden of ["node:http", "node:https", "fetch(", "undici", "node-fetch", "node:net", "node:dgram"]) {
      expect(`${forbidden}:${source.includes(forbidden)}`).toBe(`${forbidden}:false`);
    }
  });

  it("performs no network access of its own", () => {
    // Asserted on this file's own import list rather than on forbidden
    // substrings: the substring form would match the very array that names the
    // forbidden modules a few assertions above.
    const imported = new Set(
      [...readText(TEST_FILE).matchAll(/^import [^;]*? from "([^"]+)";$/gm)].map((m) => m[1])
    );
    expect([...imported].sort()).toEqual([
      "./migration-inventory",
      "node:child_process",
      "node:crypto",
      "node:fs",
      "node:path",
      "node:url",
      "vitest",
    ]);
  });
});

describe("EQ-S2-C v2 — candidate migration safety", () => {
  it("serializes as LF-only UTF-8 with exactly one trailing newline", () => {
    expect(emittedSql.length).toBeGreaterThan(0);
    expect(emittedSql.includes("\r")).toBe(false);
    expect(emittedSql.endsWith("\n")).toBe(true);
    expect(emittedSql.endsWith("\n\n")).toBe(false);
    expect(emittedSql.charCodeAt(0)).not.toBe(0xfeff);
  });

  it("is transactional", () => {
    expect(emittedSql).toContain("\nbegin;\n");
    expect(emittedSql.trimEnd().endsWith("commit;")).toBe(true);
  });

  it("is append-only: no UPDATE, DELETE, TRUNCATE or DROP", () => {
    const lowered = emittedSql.toLowerCase();
    for (const forbidden of ["update ", "delete from", "truncate", "drop "]) {
      expect(`${forbidden.trim()}:${lowered.includes(forbidden)}`).toBe(`${forbidden.trim()}:false`);
    }
  });

  it("contains no DDL, RLS or grant change", () => {
    const lowered = emittedSql.toLowerCase();
    for (const forbidden of [
      "alter table", "create table", "create index", "create type", "create policy",
      "create function", "create or replace", "grant ", "revoke ", "security definer",
      "enable row level security",
    ]) {
      expect(`${forbidden.trim()}:${lowered.includes(forbidden)}`).toBe(`${forbidden.trim()}:false`);
    }
  });

  it("inserts into exactly the two intended tables, and never a manufacturer, putter spec or user row", () => {
    const inserts = emittedSql.match(/^insert into ([a-z_.]+)/gm) ?? [];
    expect(inserts).toEqual([
      "insert into public.equipment_models",
      "insert into public.equipment_model_sources",
    ]);
    for (const table of [
      "public.equipment_manufacturers",
      "public.equipment_putter_model_specs",
      "public.user_equipment",
      "public.swing_analysis",
      "public.swings",
      "public.profiles",
    ]) {
      expect(`${table}:${emittedSql.includes(`insert into ${table}`)}`).toBe(`${table}:false`);
    }
  });

  it("inserts exactly 201 model rows and 201 source rows", () => {
    const modelRows =
      emittedSql.match(
        /^ {2}\('[0-9a-f-]{36}', \(select id from public\.equipment_manufacturers where slug = '[a-z]+'\)/gm
      ) ?? [];
    const sourceRows =
      emittedSql.match(/^ {2}\('[0-9a-f-]{36}', '[0-9a-f-]{36}', 'official_[a-z_]+',/gm) ?? [];
    expect(modelRows).toHaveLength(EXPECTED_MODEL_COUNT);
    expect(sourceRows).toHaveLength(EXPECTED_SOURCE_COUNT);
  });

  it("asserts the locked preconditions", () => {
    for (const marker of [
      "EQ2SC-PRE-1", "EQ2SC-PRE-2", "EQ2SC-PRE-3", "EQ2SC-PRE-4", "EQ2SC-PRE-5",
      "EQ2SC-PRE-6", "EQ2SC-PRE-7", "EQ2SC-PRE-8", "EQ2SC-PRE-9", "EQ2SC-PRE-10",
      "EQ2SC-PRE-11", "EQ2SC-PRE-12", "EQ2SC-PRE-13", "EQ2SC-PRE-14", "EQ2SC-PRE-15",
    ]) {
      expect(emittedSql).toContain(marker);
    }
    expect(emittedSql).toContain("equipment_models_catalog_key_unique");
    expect(emittedSql).toContain("equipment_models_slug_unique");
    expect(emittedSql).toContain("equipment_models_manufacturer_type_name_year_uidx");
    expect(emittedSql).toContain("club_type_enum");
    expect(emittedSql).toContain(
      `expected exactly ${EXPECTED_EXISTING_COUNT} existing equipment_models rows`
    );
    expect(emittedSql).toContain("expected exactly 30 existing non-Putter models");
    expect(emittedSql).toContain("expected exactly 21 existing Putter models");
    expect(emittedSql).toContain("expected exactly 6 equipment_manufacturers rows");
  });

  it("asserts the locked postconditions and projected totals", () => {
    for (const marker of [
      "EQ2SC-POST-1", "EQ2SC-POST-2", "EQ2SC-POST-3", "EQ2SC-POST-4", "EQ2SC-POST-5",
      "EQ2SC-POST-6", "EQ2SC-POST-7", "EQ2SC-POST-8", "EQ2SC-POST-9", "EQ2SC-POST-10",
      "EQ2SC-POST-11", "EQ2SC-POST-12", "EQ2SC-POST-13", "EQ2SC-POST-14", "EQ2SC-POST-15",
    ]) {
      expect(emittedSql).toContain(marker);
    }
    expect(emittedSql).toContain(`expected exactly ${EXPECTED_COMBINED_COUNT} equipment_models rows`);
    expect(emittedSql).toContain("expected exactly 231 non-Putter models");
    expect(emittedSql).toContain(
      `expected exactly ${EXPECTED_COMBINED_COUNT} equipment_model_sources rows`
    );
    expect(emittedSql).toContain("expected exactly 21 equipment_putter_model_specs rows");
    for (const [clubType, expected] of Object.entries(EXPECTED_POST_CLUB_TYPE_TOTALS)) {
      expect(emittedSql).toContain(`expected exactly ${expected} ${clubType} models`);
    }
  });

  it("guards user_equipment on non-null equipment_model_id only, never on total row count", () => {
    expect(emittedSql).toContain(
      "select count(*) into v_count from public.user_equipment where equipment_model_id is not null;"
    );
    expect(emittedSql.includes("select count(*) into v_count from public.user_equipment;")).toBe(false);
  });

  it("preserves the closed v1 baseline by exact catalog-key and slug set", () => {
    for (const model of existingModels) {
      expect(emittedSql).toContain(sqlString(model.catalog_key));
      expect(emittedSql).toContain(sqlString(model.slug));
    }
    expect(emittedSql).toContain("the original 51 catalog_key set is no longer intact");
    expect(emittedSql).toContain("the original 51 slug set is no longer intact");
  });
});

// ---------------------------------------------------------------------------
// EQ-S2-B2 live-database prerequisite
//
// One of the 201 provenance rows uses official_category_page, a class that only
// exists once EQ-S2-B2 has widened the source-type CHECK from three values to
// four. Applying this delta to a database still carrying the three-value rule
// would fail mid-INSERT on a bare constraint violation.
//
// Every assertion below runs against EXECUTABLE SQL with comment lines stripped,
// so a guard that exists only as prose cannot satisfy any of them.
// ---------------------------------------------------------------------------

const B2_CONSTRAINT_NAME = "equipment_model_sources_type_check";
const B2_ADMITTED_SOURCE_TYPES = [
  "official_archive",
  "official_category_page",
  "official_product_page",
  "official_spec_pdf",
];
const B2_SIBLING_CONSTRAINTS = [
  "equipment_model_sources_url_https",
  "equipment_model_sources_verified_not_future",
  "equipment_model_sources_model_url_unique",
];

function stripSqlComments(sql: string): string {
  return sql
    .split("\n")
    .filter((line) => !/^\s*--/.test(line))
    .join("\n");
}

const executableSql = stripSqlComments(emittedSql);

describe("EQ-S2-C v2 — EQ-S2-B2 live prerequisite", () => {
  it("strips to executable SQL that still carries both guards", () => {
    expect(executableSql.includes("--")).toBe(false);
    expect(executableSql).toContain("EQ2SC-B2PRE-A:");
    expect(executableSql).toContain("EQ2SC-B2POST-A:");
  });

  it("names the exact B2 constraint in both guards", () => {
    const occurrences = (
      executableSql.match(new RegExp(`con\\.conname = '${B2_CONSTRAINT_NAME}'`, "g")) ?? []
    ).length;
    expect(occurrences).toBe(2);
    expect(executableSql).toContain(
      `raise exception 'EQ2SC-B2PRE-C: constraint ${B2_CONSTRAINT_NAME} is missing.`
    );
    expect(executableSql).toContain(
      `raise exception 'EQ2SC-B2POST-C: constraint ${B2_CONSTRAINT_NAME} is missing.`
    );
  });

  it("requires exactly one CHECK constraint governing source_type", () => {
    const shape =
      "       and pg_get_constraintdef(con.oid, false) ~ '\\msource_type\\M'\n  ) <> 1 then";
    expect((executableSql.split(shape).length - 1)).toBe(2);
    for (const code of ["EQ2SC-B2PRE", "EQ2SC-B2POST"]) {
      expect(executableSql).toContain(
        `raise exception '${code}-B: public.equipment_model_sources does not have exactly one source_type CHECK constraint.'`
      );
    }
  });

  it("enforces exact four-literal set equality, not substring presence", () => {
    // The expected array is declared literally in each guard, and compared as a
    // sorted de-duplicated set — a rule that merely mentions a class fails.
    const expectedArray =
      "  v_expected  text[] := array[\n" +
      B2_ADMITTED_SOURCE_TYPES.map((t, i) => `    '${t}'${i === 3 ? "" : ","}`).join("\n") +
      "\n  ];";
    expect(executableSql.split(expectedArray).length - 1).toBe(2);

    const setEquality =
      "if v_found is distinct from (select array_agg(x order by x) from unnest(v_expected) as x) then";
    expect(executableSql.split(setEquality).length - 1).toBe(2);

    const literalCount =
      "  select count(*) into v_literals\n    from regexp_matches(v_norm, '''([^'']*)''', 'g');";
    expect(executableSql.split(literalCount).length - 1).toBe(2);
    expect(executableSql.split("if v_literals <> array_length(v_expected, 1) then").length - 1).toBe(2);
  });

  it("validates the membership-predicate shape", () => {
    expect(executableSql.split("if v_norm !~ '^CHECK ' then").length - 1).toBe(2);
    expect(
      executableSql.split("if v_norm !~ '= ANY' and v_norm !~ '\\mIN\\M' then").length - 1
    ).toBe(2);
    for (const code of ["EQ2SC-B2PRE", "EQ2SC-B2POST"]) {
      expect(executableSql).toContain(`${code}-D: the source_type rule is not a CHECK expression.`);
      expect(executableSql).toContain(
        `${code}-E: the source_type rule is not a simple membership predicate.`
      );
    }
  });

  it("rejects any extra boolean or comparison logic once literals are blanked", () => {
    const blanking = "  v_blank := upper(regexp_replace(v_norm, '''[^'']*''', ' ', 'g'));";
    expect(executableSql.split(blanking).length - 1).toBe(2);
    for (const token of [
      "v_blank ~ '\\mOR\\M'",
      "v_blank ~ '\\mAND\\M'",
      "v_blank ~ '\\mNOT\\M'",
      "v_blank ~ '\\mIS\\M'",
      "v_blank ~ '\\mLIKE\\M'",
      "v_blank ~ '\\mILIKE\\M'",
      "v_blank ~ '\\mSIMILAR\\M'",
      "v_blank ~ '[<>]'",
      "v_blank ~ '!='",
      "v_blank ~ '~'",
    ]) {
      expect(`${token}:${executableSql.split(token).length - 1}`).toBe(`${token}:2`);
    }
  });

  it("requires source_type to be referenced exactly once as the governed column", () => {
    const guard =
      "if (select count(*) from regexp_matches(v_blank, '\\mSOURCE_TYPE\\M', 'g')) <> 1 then";
    expect(executableSql.split(guard).length - 1).toBe(2);
    for (const code of ["EQ2SC-B2PRE", "EQ2SC-B2POST"]) {
      expect(executableSql).toContain(
        `${code}-G: the source_type rule does not reference source_type exactly once.`
      );
    }
  });

  it("refuses participation by any second column of the provenance table", () => {
    const loop =
      "  for v_col in\n" +
      "    select att.attname\n" +
      "      from pg_attribute att\n" +
      "      join pg_class rel on rel.oid = att.attrelid\n" +
      "      join pg_namespace nsp on nsp.oid = rel.relnamespace\n" +
      "     where nsp.nspname = 'public'\n" +
      "       and rel.relname = 'equipment_model_sources'\n" +
      "       and att.attnum > 0\n" +
      "       and not att.attisdropped\n" +
      "       and att.attname <> 'source_type'\n" +
      "  loop";
    expect(executableSql.split(loop).length - 1).toBe(2);
    expect(
      executableSql.split("if v_blank ~ ('\\m' || upper(v_col) || '\\M') then").length - 1
    ).toBe(2);
  });

  it("checks all three sibling provenance constraints in each guard", () => {
    for (const conname of B2_SIBLING_CONSTRAINTS) {
      const occurrences = (
        executableSql.match(new RegExp(`con\\.conname = '${conname}'`, "g")) ?? []
      ).length;
      expect(`${conname}:${occurrences}`).toBe(`${conname}:2`);
    }
    for (const code of ["EQ2SC-B2PRE", "EQ2SC-B2POST"]) {
      expect(executableSql).toContain(
        `${code}-L: a sibling constraint on public.equipment_model_sources is missing.`
      );
    }
  });

  it("requires the provenance table to be an ordinary table", () => {
    expect(executableSql.split("and rel.relkind = 'r'").length - 1).toBe(2);
  });

  it("carries every lettered check A through L in both guards", () => {
    for (const code of ["EQ2SC-B2PRE", "EQ2SC-B2POST"]) {
      for (const letter of ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]) {
        expect(`${code}-${letter}:${executableSql.includes(`${code}-${letter}:`)}`).toBe(
          `${code}-${letter}:true`
        );
      }
    }
  });

  it("places the prerequisite guard before the first INSERT", () => {
    const preGuard = executableSql.indexOf("EQ2SC-B2PRE-A:");
    const modelInsert = executableSql.indexOf("\ninsert into public.equipment_models (");
    const sourceInsert = executableSql.indexOf("\ninsert into public.equipment_model_sources (");
    expect(preGuard).toBeGreaterThan(-1);
    expect(modelInsert).toBeGreaterThan(-1);
    expect(preGuard).toBeLessThan(modelInsert);
    expect(preGuard).toBeLessThan(sourceInsert);
    // ...and after the transaction opens, so a failure rolls back cleanly.
    expect(preGuard).toBeGreaterThan(executableSql.indexOf("\nbegin;"));
  });

  it("places the preservation guard after the provenance INSERT and before commit", () => {
    const postGuard = executableSql.indexOf("EQ2SC-B2POST-A:");
    const sourceInsert = executableSql.indexOf("\ninsert into public.equipment_model_sources (");
    const commitAt = executableSql.lastIndexOf("\ncommit;");
    expect(postGuard).toBeGreaterThan(sourceInsert);
    expect(postGuard).toBeLessThan(commitAt);
  });

  it("performs zero schema mutation against the B2 rule", () => {
    const lowered = executableSql.toLowerCase();
    for (const forbidden of [
      "drop constraint",
      "add constraint",
      "alter constraint",
      "validate constraint",
      "alter table",
    ]) {
      expect(`${forbidden}:${lowered.includes(forbidden)}`).toBe(`${forbidden}:false`);
    }
  });

  it("still emits exactly one official_category_page data row", () => {
    const dataRow = `'official_category_page', '${SOLE_CATEGORY_PAGE_SOURCE.source_name}', '${SOLE_CATEGORY_PAGE_SOURCE.source_url}'`;
    expect(executableSql.split(dataRow).length - 1).toBe(1);
    // Three total occurrences of the class literal: one inserted row, plus the
    // expected-set array in each of the two guards.
    expect((executableSql.match(/'official_category_page'/g) ?? []).length).toBe(3);
  });

  it("keeps the generator vocabulary and the B2 admitted set identical", () => {
    expect([...Object.keys(EXPECTED_SOURCE_TYPE_DISTRIBUTION)].sort()).toEqual(
      [...B2_ADMITTED_SOURCE_TYPES].sort()
    );
  });
});

// ---------------------------------------------------------------------------
// The materialized migration
//
// The migration filename is CLI-generated and must never be fabricated here, so
// every assertion reaches it through EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME
// in the shared inventory rather than through a literal in this file.
// ---------------------------------------------------------------------------

const MIGRATIONS_DIR = "supabase/migrations";
const V2_MIGRATION_SUFFIX = "_equipment_non_putter_catalog_v2.sql";

const migrationFilenames = readdirSync(path.join(repoRoot, MIGRATIONS_DIR))
  .filter((name) => name.endsWith(".sql"))
  .sort();

const v2MigrationMatches = migrationFilenames.filter((name) =>
  name.endsWith(V2_MIGRATION_SUFFIX)
);

describe("EQ-S2-C v2 — materialized migration", () => {
  it("ships exactly one v2 catalog migration", () => {
    expect(v2MigrationMatches).toHaveLength(1);
  });

  it("carries the CLI-generated filename recorded in the shared inventory", () => {
    expect(v2MigrationMatches[0]).toBe(EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME);
    expect(/^\d{14}_equipment_non_putter_catalog_v2\.sql$/.test(EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME)).toBe(
      true
    );
  });

  it("sorts strictly after every migration authored before it", () => {
    const earlier = migrationsAuthoredBefore(EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME);
    expect(earlier).toHaveLength(APPROVED_MIGRATIONS.length - 1);
    expect(sortsAfterAll(EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME, earlier)).toBe(true);
  });

  it("is byte-identical to the generator output", () => {
    const onDisk = readBytes(`${MIGRATIONS_DIR}/${EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME}`);
    expect(onDisk.toString("utf8")).toBe(emittedSql);
    expect(sha256(onDisk)).toBe(sha256(Buffer.from(emittedSql, "utf8")));
  });

  it("passes generator --check against the committed migration", () => {
    const output = execFileSync(
      process.execPath,
      [path.join(repoRoot, GENERATOR_FILE), "--check"],
      { cwd: repoRoot, maxBuffer: 16 * 1024 * 1024 }
    ).toString("utf8");
    expect(output).toContain("matches the generated output byte-for-byte");
    expect(output).toContain(EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME);
  });

  it("serializes as LF-only UTF-8 with no BOM and exactly one terminal LF", () => {
    const bytes = readBytes(`${MIGRATIONS_DIR}/${EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME}`);
    const text = bytes.toString("utf8");
    expect(text.includes("\r")).toBe(false);
    expect(bytes[0]).not.toBe(0xef);
    expect(text.charCodeAt(0)).not.toBe(0xfeff);
    expect(text.endsWith("\n")).toBe(true);
    expect(text.endsWith("\n\n")).toBe(false);
  });

  it("appears exactly once in the approved migration inventory", () => {
    const occurrences = APPROVED_MIGRATIONS.filter(
      (name) => name === EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME
    );
    expect(occurrences).toHaveLength(1);
  });

  it("keeps the inventory and the migrations directory an exact set match", () => {
    expect([...APPROVED_MIGRATIONS].sort()).toEqual(migrationFilenames);
    expect(new Set(APPROVED_MIGRATIONS).size).toBe(APPROVED_MIGRATIONS.length);
  });

  it("derives the expected migration count as 31", () => {
    expect(EXPECTED_MIGRATION_COUNT).toBe(APPROVED_MIGRATIONS.length);
    expect(EXPECTED_MIGRATION_COUNT).toBe(31);
    expect(migrationFilenames).toHaveLength(31);
  });

  it("remains data-only in its executable SQL", () => {
    const materialized = stripSqlComments(
      readText(`${MIGRATIONS_DIR}/${EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME}`)
    );
    const lowered = materialized.toLowerCase();
    for (const forbidden of [
      "create table", "alter table", "drop table", "drop constraint", "add constraint",
      "truncate", "update ", "delete from", "delete ", "grant ", "revoke ",
      "create policy", "drop policy", "security definer", "create index", "create type",
      "create or replace", "insert into public.equipment_manufacturers",
      "insert into public.user_equipment", "insert into public.equipment_putter_model_specs",
    ]) {
      expect(`${forbidden.trim()}:${lowered.includes(forbidden)}`).toBe(`${forbidden.trim()}:false`);
    }
    const inserts = materialized.match(/^insert into ([a-z_.]+)/gm) ?? [];
    expect(inserts).toEqual([
      "insert into public.equipment_models",
      "insert into public.equipment_model_sources",
    ]);
  });

  it("keeps both EQ-S2-B2 guards in the materialized executable SQL", () => {
    const materialized = stripSqlComments(
      readText(`${MIGRATIONS_DIR}/${EQUIPMENT_NON_PUTTER_CATALOG_V2_FILENAME}`)
    );
    for (const code of ["EQ2SC-B2PRE", "EQ2SC-B2POST"]) {
      for (const letter of ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]) {
        expect(`${code}-${letter}:${materialized.includes(`${code}-${letter}:`)}`).toBe(
          `${code}-${letter}:true`
        );
      }
    }
    expect(
      (materialized.match(new RegExp(`con\.conname = '${B2_CONSTRAINT_NAME}'`, "g")) ?? []).length
    ).toBe(2);
    for (const conname of B2_SIBLING_CONSTRAINTS) {
      expect(
        (materialized.match(new RegExp(`con\.conname = '${conname}'`, "g")) ?? []).length
      ).toBe(2);
    }
    const preGuard = materialized.indexOf("EQ2SC-B2PRE-A:");
    const postGuard = materialized.indexOf("EQ2SC-B2POST-A:");
    const modelInsert = materialized.indexOf("\ninsert into public.equipment_models (");
    const sourceInsert = materialized.indexOf("\ninsert into public.equipment_model_sources (");
    const commitAt = materialized.lastIndexOf("\ncommit;");
    expect(preGuard).toBeLessThan(modelInsert);
    expect(postGuard).toBeGreaterThan(sourceInsert);
    expect(postGuard).toBeLessThan(commitAt);
  });
});
