/**
 * SwingProAI — GPS / Golf Terrain Service
 *
 * Environment-aware wrapper for golf GPS and green undulation data.
 * Set USE_MOCK_GPS=true in .env.local or Vercel env vars to bypass
 * external API calls during development and load testing.
 *
 * Production providers: Golf Intelligence API, iGolf, Hole19
 */

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface GreenUndulationData {
  holeNumber: number;
  /** 2D grid of elevation offsets in inches, row-major (front-to-back × left-to-right) */
  elevationGrid: number[][];
  gridResolutionFeet: number;
  /** Summary generated by provider or AI */
  narrativeSummary: string;
  /** Optimal landing zones for approach shots */
  recommendedLandingZones: { x: number; y: number; radiusFeet: number; label: string }[];
  dataSourcedAt: string;
}

export interface HazardMatrix {
  holeNumber: number;
  hazards: {
    id: string;
    type: "water" | "bunker" | "ob" | "trees" | "rough" | "penalty_area";
    polygon: { lat: number; lng: number }[];
    centerLat: number;
    centerLng: number;
    distanceFromTeeYards: number;
    carryRequiredYards?: number;
    label: string;
  }[];
}

export interface CourseTerrainData {
  courseProviderId: string;
  courseName: string;
  holes: {
    holeNumber: number;
    undulation: GreenUndulationData;
    hazards: HazardMatrix;
  }[];
  fetchedAt: string;
}

// ─── Mock Data Factory ────────────────────────────────────────────────────────

function buildMockUndulation(holeNumber: number): GreenUndulationData {
  // Generate a plausible 5×5 elevation grid
  const grid = Array.from({ length: 5 }, (_, row) =>
    Array.from({ length: 5 }, (_, col) => {
      const base = (holeNumber % 3) * 0.5;
      return parseFloat((base + row * 0.3 - col * 0.2 + Math.sin(row + col) * 0.4).toFixed(2));
    })
  );

  return {
    holeNumber,
    elevationGrid: grid,
    gridResolutionFeet: 8,
    narrativeSummary:
      holeNumber % 3 === 0
        ? "Severe front-to-back slope. Short misses collect into false front."
        : holeNumber % 3 === 1
        ? "Left-to-right tilt with back-right pin position running away. Two-putt zone is front-center."
        : "Relatively flat green with subtle borrow from right. Plays truer than it looks.",
    recommendedLandingZones: [
      { x: 2, y: 1, radiusFeet: 12, label: "Ideal — center-left" },
      { x: 2, y: 2, radiusFeet: 20, label: "Safe — center" },
    ],
    dataSourcedAt: new Date().toISOString(),
  };
}

function buildMockHazards(holeNumber: number): HazardMatrix {
  return {
    holeNumber,
    hazards: [
      {
        id: `mock-bunker-${holeNumber}-L`,
        type: "bunker",
        polygon: [],
        centerLat: 33.0 + holeNumber * 0.001,
        centerLng: -117.0 + holeNumber * 0.001,
        distanceFromTeeYards: 220 + holeNumber * 2,
        carryRequiredYards: 225 + holeNumber * 2,
        label: "Left fairway bunker",
      },
      {
        id: `mock-water-${holeNumber}-R`,
        type: "water",
        polygon: [],
        centerLat: 33.001 + holeNumber * 0.001,
        centerLng: -117.001 + holeNumber * 0.001,
        distanceFromTeeYards: 280 + holeNumber,
        label: "Right lateral hazard",
      },
    ],
  };
}

function buildMockCourseData(courseProviderId: string): CourseTerrainData {
  return {
    courseProviderId,
    courseName: `[MOCK] Course ${courseProviderId}`,
    holes: Array.from({ length: 18 }, (_, i) => ({
      holeNumber: i + 1,
      undulation: buildMockUndulation(i + 1),
      hazards: buildMockHazards(i + 1),
    })),
    fetchedAt: new Date().toISOString(),
  };
}

// ─── Live Provider Fetch ───────────────────────────────────────────────────────

async function fetchLiveCourseData(courseProviderId: string): Promise<CourseTerrainData> {
  const apiKey = process.env.GOLF_GPS_API_KEY;
  const baseUrl = process.env.GOLF_GPS_API_URL ?? "https://api.golfgenius.com/v3";

  if (!apiKey) {
    throw new Error("GOLF_GPS_API_KEY is not configured. Set USE_MOCK_GPS=true to use mock data.");
  }

  const response = await fetch(`${baseUrl}/courses/${courseProviderId}/terrain`, {
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
    next: { revalidate: 86400 }, // 24-hour ISR cache
  });

  if (!response.ok) {
    throw new Error(`GPS provider returned ${response.status} for course ${courseProviderId}`);
  }

  const raw = await response.json();

  // Normalize provider response to our internal schema
  return {
    courseProviderId,
    courseName: raw.name ?? courseProviderId,
    holes: (raw.holes ?? []).map((h: Record<string, unknown>) => ({
      holeNumber: h.number,
      undulation: {
        holeNumber: h.number,
        elevationGrid: (h.green_grid as number[][]) ?? [],
        gridResolutionFeet: (h.grid_res_ft as number) ?? 10,
        narrativeSummary: (h.undulation_summary as string) ?? "",
        recommendedLandingZones: [],
        dataSourcedAt: new Date().toISOString(),
      },
      hazards: {
        holeNumber: h.number as number,
        hazards: ((h.hazards as Record<string, unknown>[]) ?? []).map((hz: Record<string, unknown>) => ({
          id: hz.id as string,
          type: hz.type as HazardMatrix["hazards"][0]["type"],
          polygon: (hz.polygon as { lat: number; lng: number }[]) ?? [],
          centerLat: hz.center_lat as number,
          centerLng: hz.center_lng as number,
          distanceFromTeeYards: hz.dist_yards as number,
          label: hz.label as string,
        })),
      },
    })),
    fetchedAt: new Date().toISOString(),
  };
}

// ─── Public API ────────────────────────────────────────────────────────────────

/**
 * Fetches terrain and hazard data for a golf course.
 * Automatically uses mock data when USE_MOCK_GPS=true.
 * In production, fetches from the configured GPS provider and caches in Supabase.
 */
export async function getCourseTerrainData(
  courseProviderId: string
): Promise<CourseTerrainData> {
  const useMock = process.env.USE_MOCK_GPS === "true";

  if (useMock) {
    console.info(`[GPS Service] Using MOCK data for course ${courseProviderId}`);
    return buildMockCourseData(courseProviderId);
  }

  return fetchLiveCourseData(courseProviderId);
}

/**
 * Returns a single hole's undulation data.
 */
export async function getHoleUndulation(
  courseProviderId: string,
  holeNumber: number
): Promise<GreenUndulationData | null> {
  const data = await getCourseTerrainData(courseProviderId);
  return data.holes.find((h) => h.holeNumber === holeNumber)?.undulation ?? null;
}

/**
 * Returns a single hole's hazard matrix.
 */
export async function getHoleHazards(
  courseProviderId: string,
  holeNumber: number
): Promise<HazardMatrix | null> {
  const data = await getCourseTerrainData(courseProviderId);
  return data.holes.find((h) => h.holeNumber === holeNumber)?.hazards ?? null;
}
